#docker compose up -d  mysql 
version: "3.9"
services:
  mysql:
    container_name: mysql_container_bk
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=password
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3307"
    volumes:
      - ./docker-volumes/datadir:/var/lib/mysql


